services:
  cms.admin.cms_site:
    class: WebEtDesign\CmsBundle\Admin\CmsSiteAdmin
    arguments: [~, WebEtDesign\CmsBundle\Entity\CmsSite, WebEtDesign\CmsBundle\Controller\Admin\CmsSiteAdminController, '%wd_cms.cms%']
    tags:
      - { name: sonata.admin, manager_type: orm, group: CMS, label: Sites}
    calls:
      - [ setTranslationDomain, [ 'wd_cms' ] ]
    public: true

  cms.admin.cms_route:
    class: WebEtDesign\CmsBundle\Admin\CmsRouteAdmin
    arguments: [~, WebEtDesign\CmsBundle\Entity\CmsRoute, WebEtDesign\CmsBundle\Controller\Admin\CmsRouteAdminController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: CMS, label: Routes, show_in_dashboard: false }
    public: true

  cms.admin.cms_page:
    class: WebEtDesign\CmsBundle\Admin\CmsPageAdmin
    arguments:
      - ~
      - WebEtDesign\CmsBundle\Entity\CmsPage
      - WebEtDesign\CmsBundle\Controller\Admin\CmsPageAdminController
      - '@doctrine.orm.default_entity_manager'
      - '%wd_cms.cms%'
      - '%wd_cms.vars%'
      - '@cms.page_provider'
      - '%wd_cms.custom_contents_form_themes%'
    tags:
      - { name: sonata.admin, manager_type: orm, group: CMS, label: Pages }
    calls:
      - [setTranslationDomain, [ 'wd_cms' ] ]
      - [setTemplate, ['edit', 'WebEtDesignCmsBundle:admin/page:edit.html.twig']]
      - [addChild, ['@cms.admin.cms_page_declination', 'declination']]
    public: true

  cms.admin.cms_content:
    class: WebEtDesign\CmsBundle\Admin\CmsContentAdmin
    arguments:
      - ~
      - WebEtDesign\CmsBundle\Entity\CmsContent
      - WebEtDesign\CmsBundle\Controller\Admin\CmsContentAdminController
      - '@doctrine.orm.default_entity_manager'
      - '%wd_cms.custom_contents%'
      - '@service_container'
      - '@cms.block_provider'
      - '@cms.page_provider'
    tags:
      - { name: sonata.admin, manager_type: orm, group: CMS, label: Contents, show_in_dashboard: false }
    calls:
      - [ setTranslationDomain, [ 'wd_cms' ] ]
    public: true

  cms.admin.cms_menu:
    class: WebEtDesign\CmsBundle\Admin\CmsMenuAdmin
    arguments:
      - ~
      - WebEtDesign\CmsBundle\Entity\CmsMenu
      - WebEtDesign\CmsBundle\Controller\Admin\CmsMenuAdminController
      - '@doctrine.orm.default_entity_manager'
      - '@cms.page_provider'
    tags:
      - { name: sonata.admin, manager_type: orm, group: CMS, label: Menus }
    calls:
      - [setTranslationDomain, ['wd_cms']]
      #      - [setTemplate, ['list', '@@WebEtDesignCms/menu/list.html.twig']]
      - [setTemplate, ['button_create', '@@WebEtDesignCms/admin/menu/actionButtons/button_create.html.twig']]
      - [setTemplate, ['edit', 'WebEtDesignCmsBundle:admin/menu:edit.html.twig']]
      - [addChild, ['@cms.admin.cms_menu_item', 'menu']]
    public: true

  cms.admin.cms_menu_item:
    class: WebEtDesign\CmsBundle\Admin\CmsMenuItemAdmin
    arguments:
      - ~
      - WebEtDesign\CmsBundle\Entity\CmsMenuItem
      - WebEtDesign\CmsBundle\Controller\Admin\CmsMenuItemAdminController
      - '@doctrine.orm.default_entity_manager'
      - '@cms.page_provider'
      - '%wd_cms.menu%'
    tags:
      - { name: sonata.admin, manager_type: orm, group: CMS, label: MenuItem, show_in_dashboard: false }
    calls:
      - [ setTranslationDomain, [ 'wd_cms' ] ]
      - [setTemplate, ['edit', '@@WebEtDesignCms/admin/menuItem/edit.html.twig']]
    public: true


  cms.admin.cms_shared_block:
    class: WebEtDesign\CmsBundle\Admin\CmsSharedBlockAdmin
    arguments:
      - ~
      - WebEtDesign\CmsBundle\Entity\CmsSharedBlock
      - WebEtDesign\CmsBundle\Controller\Admin\CmsSharedBlockAdminController
      - '@doctrine.orm.default_entity_manager'
      - '%wd_cms.cms%'
      - '%wd_cms.custom_contents_form_themes%'
    tags:
      - { name: sonata.admin, manager_type: orm, group: CMS, label: Blocs partagés }
    calls:
      - [ setTranslationDomain, [ 'wd_cms' ] ]
      - [setTemplate, ['list', '@@WebEtDesignCms/admin/sharedBlock/list.html.twig']]
      - [setTemplate, ['button_create', '@@WebEtDesignCms/admin/sharedBlock/actionButtons/button_create.html.twig']]

    public: true

  cms.admin.cms_content_has_shared_block:
    class: WebEtDesign\CmsBundle\Admin\CmsContentHasSharedBlockAdmin
    arguments:
      - ~
      - WebEtDesign\CmsBundle\Entity\CmsContentHasSharedBlock
      - ~
    tags:
      - { name: sonata.admin, manager_type: orm, group: CMS, label: content has sharedBlock, show_in_dashboard: false }
    public: true

  WebEtDesign\CmsBundle\Admin\CmsPageDeclinationAdmin:
    arguments:
      - ~
      - WebEtDesign\CmsBundle\Entity\CmsPageDeclination
      - WebEtDesign\CmsBundle\Controller\Admin\CmsPageDeclinationAdminController
      - '@doctrine.orm.default_entity_manager'
      - '%wd_cms.templates%'
      - '%wd_cms.vars%'
      - '%wd_cms.custom_contents_form_themes%'
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'CMS', label: 'Page déclinaison', show_in_dashboard: false }
    calls:
      - [ setTranslationDomain, [ 'wd_cms' ] ]
    public: true

  cms.admin.cms_page_declination:
    alias: WebEtDesign\CmsBundle\Admin\CmsPageDeclinationAdmin
