services:
  _defaults:
    autowire:      true
    autoconfigure: true

  cms.admin.cms_site:
    class: WebEtDesign\CmsBundle\Admin\CmsSiteAdmin
    tags:
      - { name: sonata.admin, model_class: WebEtDesign\CmsBundle\Entity\CmsSite, controller:  WebEtDesign\CmsBundle\Controller\Admin\CmsSiteAdminController, manager_type: orm, group: CMS, label: Sites}
    calls:
      - [ setTranslationDomain, [ 'wd_cms' ] ]
      - [ addChild, [ '@cms.admin.cms_page', 'site' ] ]
      - [ addChild, [ '@cms.admin.cms_shared_block', 'site' ] ]
      - [ addChild, [ '@cms.admin.cms_menu', 'site' ] ]
    public: true

  cms.admin.cms_route:
    class: WebEtDesign\CmsBundle\Admin\CmsRouteAdmin
    tags:
      - { name: sonata.admin, model_class: WebEtDesign\CmsBundle\Entity\CmsRoute, controller: WebEtDesign\CmsBundle\Controller\Admin\CmsRouteAdminController, manager_type: orm, group: CMS, label: Routes, show_in_dashboard: false }
    public: true

  cms.admin.cms_page:
    class: WebEtDesign\CmsBundle\Admin\CmsPageAdmin
    tags:
      - { name: sonata.admin, model_class: WebEtDesign\CmsBundle\Entity\CmsPage, controller: WebEtDesign\CmsBundle\Controller\Admin\CmsPageAdminController, manager_type: orm, group: CMS, label: Pages, label_translator_strategy: sonata.admin.label.strategy.underscore }
    calls:
      - [setTranslationDomain, [ 'wd_cms' ] ]
      - [setTemplate, ['edit', '@@WebEtDesignCms/admin/page/edit.html.twig']]
      - [setTemplate, ['tree', '@@WebEtDesignCms/admin/page/tree.html.twig']]
      - [addChild, ['@cms.admin.cms_page_declination', 'page']]
    public: true

  cms.admin.cms_content:
    class: WebEtDesign\CmsBundle\Admin\CmsContentAdmin
    tags:
      - { name: sonata.admin, model_class: WebEtDesign\CmsBundle\Entity\CmsContent, controller: WebEtDesign\CmsBundle\Controller\Admin\CmsContentAdminController, manager_type: orm, group: CMS, label: Contents, show_in_dashboard: false }
    calls:
      - [ setTranslationDomain, [ 'wd_cms' ] ]
    public: true

  cms.admin.cms_menu:
    class: WebEtDesign\CmsBundle\Admin\CmsMenuAdmin
    tags:
      - { name: sonata.admin, model_class: WebEtDesign\CmsBundle\Entity\CmsMenu, controller: WebEtDesign\CmsBundle\Controller\Admin\CmsMenuAdminController, manager_type: orm, group: CMS, label: Menus, label_translator_strategy: sonata.admin.label.strategy.underscore }
    calls:
      - [setTranslationDomain, ['CmsMenuAdmin']]
      #      - [setTemplate, ['list', '@@WebEtDesignCms/menu/list.html.twig']]
      - [setTemplate, ['button_create', '@@WebEtDesignCms/admin/menu/actionButtons/button_create.html.twig']]
      - [setTemplate, ['edit', '@@WebEtDesignCms/admin/menu/edit.html.twig']]
      - [addChild, ['@cms.admin.cms_menu_item', 'menu']]
    public: true

  cms.admin.cms_menu_item:
    class: WebEtDesign\CmsBundle\Admin\CmsMenuItemAdmin
    tags:
      - { name: sonata.admin, model_class: WebEtDesign\CmsBundle\Entity\CmsMenuItem, controller: WebEtDesign\CmsBundle\Controller\Admin\CmsMenuItemAdminController, manager_type: orm, group: CMS, label: MenuItem, show_in_dashboard: false, label_translator_strategy: sonata.admin.label.strategy.underscore }
    calls:
      - [ setTranslationDomain, [ 'CmsMenuItemAdmin' ] ]
      - [setTemplate, ['edit', '@@WebEtDesignCms/admin/menuItem/edit.html.twig']]
    public: true


  cms.admin.cms_shared_block:
    class: WebEtDesign\CmsBundle\Admin\CmsSharedBlockAdmin
    tags:
      - { name: sonata.admin, model_class: WebEtDesign\CmsBundle\Entity\CmsSharedBlock, controller: WebEtDesign\CmsBundle\Controller\Admin\CmsSharedBlockAdminController, manager_type: orm, group: CMS, label: Blocs partagés, label_translator_strategy: sonata.admin.label.strategy.underscore }
    calls:
      - [ setTranslationDomain, [ 'CmsSharedBlockAdmin' ] ]
#      - [setTemplate, ['list', '@@WebEtDesignCms/admin/sharedBlock/list.html.twig']]
      - [setTemplate, ['button_create', '@@WebEtDesignCms/admin/sharedBlock/actionButtons/button_create.html.twig']]

    public: true

  WebEtDesign\CmsBundle\Admin\CmsPageDeclinationAdmin:
    tags:
      - { name: sonata.admin, model_class: WebEtDesign\CmsBundle\Entity\CmsPageDeclination, controller: WebEtDesign\CmsBundle\Controller\Admin\CmsPageDeclinationAdminController, manager_type: orm, group: 'CMS', label: 'Page déclinaison', show_in_dashboard: false }
    calls:
      - [ setTranslationDomain, [ 'wd_cms' ] ]
    public: true

  cms.admin.cms_page_declination:
    alias: WebEtDesign\CmsBundle\Admin\CmsPageDeclinationAdmin
