services:
  _defaults:
    autowire: true

  WebEtDesign\CmsBundle\Command\CmsUpdatePageParamsCommand:
    tags:
      - { name: 'console.command', command: 'cms:page:update-params' }

  WebEtDesign\CmsBundle\Command\CmsUpdateContentsSharedBlockCommand:
    tags:
      - { name: 'console.command', command: 'cms:shared-block:update-contents' }

  WebEtDesign\CmsBundle\Command\CmsDuplicateSiteCommand:
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@WebEtDesign\CmsBundle\Repository\CmsPageRepository'
      - '@WebEtDesign\CmsBundle\Repository\CmsSiteRepository'
      - ~
    tags:
      - { name: 'console.command', command: 'cms:duplicate:site' }

  WebEtDesign\CmsBundle\Command\CmsDuplicateMenuCommand:
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@WebEtDesign\CmsBundle\Repository\CmsMenuRepository'
      - '@WebEtDesign\CmsBundle\Repository\CmsMenuItemRepository'
      - '@WebEtDesign\CmsBundle\Repository\CmsSiteRepository'
      - '@WebEtDesign\CmsBundle\Repository\CmsPageRepository'
      - ~
    tags:
      - { name: 'console.command', command: 'cms:duplicate:menu' }


  WebEtDesign\CmsBundle\Command\CmsMenuIconSetGeneratorCommand:
    arguments:
      - '%wd_cms.menu.icon_set%'
    tags:
      - { name: 'console.command', command: 'cms:menu:icon-set-generator' }
