services:
  WebEtDesign\CmsBundle\Command\CmsMigrationArboCommand:
    arguments:
      - ~
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'console.command', command: 'cms:migration-arbo' }

  WebEtDesign\CmsBundle\Command\CmsGenerateContentsPositionCommand:
    arguments:
      - ~
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'console.command', command: 'cms:gen-contents-position' }

  WebEtDesign\CmsBundle\Command\CmsResetContentCommand:
    arguments:
      - ~
      - '@doctrine.orm.default_entity_manager'
      - '@cms.page_provider'
    tags:
      - { name: 'console.command', command: 'cms:reset-content' }
