services:
  WebEtDesign\CmsBundle\Form\CustomContents\SortableEntityType:
    tags: {name: form.type}
    arguments:
      ['@WebEtDesign\CmsBundle\Services\CmsSonataFormBuilderHelper']

  cms.custom_content.user:
    public: true
    class: WebEtDesign\CmsBundle\Services\EntityContent
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%wd_cms.admin.content.user%'
      - false

  cms.custom_content.users:
    public: true
    class: WebEtDesign\CmsBundle\Services\EntityContent
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%wd_cms.admin.content.user%'
      - true
