services:

  # -------------------------------
  #        FORM
  # -------------------------------

  WebEtDesign\CmsBundle\Form\CustomContents\SortableEntityType:
    tags: {name: form.type}
    arguments:
      ['@WebEtDesign\CmsBundle\Services\CmsSonataFormBuilderHelper']

  # -------------------------------
  #        Content service
  # -------------------------------

  WebEtDesign\CmsBundle\Services\CustomContents\SharedBlockContent:
    public: true
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@cms.block_provider'
      - '@twig'

  cms.content.shared_block_collection:
    public: true
    class: WebEtDesign\CmsBundle\Services\CustomContents\SortableCollection
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@twig'
      - WebEtDesign\CmsBundle\Entity\CmsSharedBlock
