services:
  cms.sonata.form_contractor.bridge:
    class: WebEtDesign\CmsBundle\Form\FormContractor
    arguments:
      - '@form.factory'

  WebEtDesign\CmsBundle\Form\Type\SecurityRolesType:
    arguments:
      - '@cms.security.editable_role_builder'
    tags:
      - { name: form.type }
