services:
  cms.admin.cms_page_listener:
    class: '%cms.admin.cms_page_listener.class%'
    arguments:
      - '@cms.page_provider'
      - '@doctrine.orm.entity_manager'
      - '@router'
      - '@filesystem'
      - '@kernel'
      - '%wd_cms.admin.config.entity.route%'
      - '%wd_cms.cms%'
      - '%wd_cms.custom_contents%'
      - '@service_container'
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postUpdate }
      - { name: doctrine.event_listener, event: preRemove }

  cms.admin.cms_page_declination_listener:
    class: WebEtDesign\CmsBundle\EventListener\PageDeclinationAdminListener
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%wd_cms.templates%'
      - '%wd_cms.cms%'
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }

  cms.admin.cms_site_listener:
    class: '%cms.admin.cms_site_listener.class%'
    arguments:
      - '@router'
      - '@filesystem'
      - '@kernel'
      - '%wd_cms.admin.config.entity.site%'
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postUpdate }

  cms.admin.cms_route_listener:
    class: WebEtDesign\CmsBundle\EventListener\RouteAdminListener
    arguments:
      - '@router'
      - '@filesystem'
      - '@kernel'
    tags:
      - { name: doctrine.event_listener, event: postUpdate }

  cms.admin.cms_menu_listener:
    class: 'WebEtDesign\CmsBundle\EventListener\MenuAdminListener'
    tags:
      - { name: doctrine.event_listener, event: postPersist }

  cms.admin.cms_shared_block_listener:
    class: '%cms.admin.cms_shared_block_listener.class%'
    arguments:
      - '@cms.block_provider'
      - '@doctrine.orm.entity_manager'
      - '@router'
      - '@filesystem'
      - '@kernel'
      - '%wd_cms.admin.config.entity.route%'
    tags:
      - { name: kernel.event_listener, event: sonata.admin.event.persistence.pre_persist, method: buildSharedBlock }

  cms.shared_bloc_listner:
    class: WebEtDesign\CmsBundle\EventListener\SharedBlockListener
    arguments:
      - '%wd_cms.custom_contents%'
      - '@service_container'
    tags:
      - { name: doctrine.event_listener, event: postLoad }


  cms.controller.listener:
    class: WebEtDesign\CmsBundle\EventListener\CmsControllerListener
    arguments:
      - '@cms.helper'
      - '@cms.page_provider'
      - '@service_container'
      - '%wd_cms.vars%'
      - '%wd_cms.cms%'
      - '@twig'
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
