services:
  cms.menu_builder:
    class: WebEtDesign\CmsBundle\Services\CmsMenuBuilder
    arguments:
      - "@knp_menu.factory"
      - "@doctrine.orm.entity_manager"
      - "@router"
      - "@security.token_storage"
      - "@security.authorization_checker"
      - "@request_stack"
      - "@service_container"
      - "%wd_cms.menu%"
    tags:
      - { name: knp_menu.menu_builder, method: cmsMenu, alias: cmsMenu }


  cms.menu_admin_builder:
    public: true
    class: WebEtDesign\CmsBundle\Services\CmsMenuAdminBuilder
    arguments:
      - "@knp_menu.factory"
      - "@doctrine.orm.entity_manager"
      - "@router"
    tags:
      - { name: knp_menu.menu_builder, method: cmsAdminMenu, alias: cmsAdminMenu }

  cms.menu_admin_renderer:
    # The class implements Knp\Menu\Renderer\RendererInterface
    class: Knp\Menu\Renderer\TwigRenderer
    arguments:
      - "@twig"
      - "@@WebEtDesignCms/menu/menu_admin_renderer.html.twig"
      - "@knp_menu.matcher"
      # add your own dependencies here
    tags:
      # The alias is what is used to retrieve the menu
      - { name: knp_menu.renderer, alias: 'cms_menu_admin_renderer' }

  cms.menu_renderer:
    class: Knp\Menu\Renderer\TwigRenderer
    arguments:
      - "@twig"
      - "@@WebEtDesignCms/menu/knp_menu.html.twig"
      - "@knp_menu.matcher"
    tags:
      # The alias is used to retrieve the menu
      - { name: knp_menu.renderer, alias: 'cms_menu_renderer' }
