services:
  cms.media.provider.image:
    public: true
    class: WebEtDesign\CmsBundle\Provider\ImageProvider
    tags:
      - { name: sonata.media.provider }
    arguments:
      - "cms.media.provider.image"
      - "@sonata.media.filesystem.local"
      - "@sonata.media.cdn.server"
      - "@sonata.media.generator.default"
      - "@sonata.media.thumbnail.format"
      - '@sonata.media.adapter.image.imagick'
      - '@sonata.media.resizer.simple'
      - ['png', 'jpg', jpeg]
      - ['image/png', 'image/jpeg']
    calls:
      - [ setTemplates, [{ helper_thumbnail: '@@SonataMedia/Provider/thumbnail.html.twig', helper_view: '@@SonataMedia/Provider/view_image.html.twig' }]]

  cms.media.provider.file:
    public: true
    class: WebEtDesign\CmsBundle\Provider\FileProvider
    tags:
      - { name: sonata.media.provider }
    arguments:
      - 'cms.media.provider.file'
      - '@sonata.media.filesystem.local'
      - '@sonata.media.cdn.server'
      - '@sonata.media.generator.default'
      - '@sonata.media.thumbnail.format'
    calls:
      - [ setTemplates, [{ helper_thumbnail: '@@SonataMedia/Provider/thumbnail.html.twig', helper_view: '@@SonataMedia/Provider/view_file.html.twig' }]]

  cms.media.provider.svg:
    public: true
    class: WebEtDesign\CmsBundle\Provider\SvgProvider
    tags:
      - { name: sonata.media.provider }
    arguments:
      - "cms.media.provider.svg"
      - "@sonata.media.filesystem.local"
      - "@sonata.media.cdn.server"
      - "@sonata.media.generator.default"
      - "@sonata.media.thumbnail.format"
      - ['svg']
      - ['image/svg+xml', 'image/svg']

    calls:
      - [ setTemplates, [{ helper_thumbnail: '@@WebEtDesignCms/provider/SVG/thumbnail.html.twig', helper_view: '@@WebEtDesignCms/provider/SVG/view_svg.html.twig' }]]

  cms.media.provider.video:
    public: true
    class: WebEtDesign\CmsBundle\Provider\VideoProvider
    tags:
      - { name: sonata.media.provider }
    arguments:
      - "cms.media.provider.video"
      - "@sonata.media.filesystem.local"
      - "@sonata.media.cdn.server"
      - "@sonata.media.generator.default"
      - "@sonata.media.thumbnail.format"
      - ['mp4','ogg','webm']
      - ['video/mp4','video/ogg','video/webm']

    calls:
      - [ setTemplates, [{ helper_thumbnail: '@@WebEtDesignCms/provider/Video/thumbnail.html.twig', helper_view: '@@WebEtDesignCms/provider/Video/view_video.html.twig' }]]
