parameters:
  cms.admin.cms_page_listener.class: WebEtDesign\CmsBundle\EventListener\PageAdminListener
  cms.admin.cms_site_listener.class: WebEtDesign\CmsBundle\EventListener\SiteAdminListener
  cms.admin.cms_shared_block_listener.class: WebEtDesign\CmsBundle\EventListener\SharedBlockAdminListener

services:
  _defaults:
    autowire: true
    autoconfigure: true

  WebEtDesign\CmsBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection'
      - '../../Entity'
      - '../../Twig'
      - '../../Sitemap'

  # ===============================================
  # REPOSITORY
  # ===============================================

  WebEtDesign\CmsBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    tags: [ 'doctrine.repository_service' ]


  # ===============================================
  # MISCELLANEOUS
  # ===============================================

  WebEtDesign\CmsBundle\EventListener\CmsBlockResizeFormListener:
    autoconfigure: false
  WebEtDesign\CmsBundle\EventListener\CmsDynamicBlockResizeFormListener:
    autoconfigure: false

  WebEtDesign\CmsBundle\Collectors\CmsCollector:
    tags:
      - name: data_collector
        template: '@WebEtDesignCms/collectors/template.html.twig'
        id: 'cms.collector'
    arguments:
      $profile: '@twig.profile'

  cms.routing_loader:
    class: WebEtDesign\CmsBundle\Routing\ExtraLoader
    public: true
    tags:
      - { name: routing.loader }


  WebEtDesign\CmsBundle\Utils\SitemapIterator:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@router'

  cms.security.editable_role_builder:
    class: WebEtDesign\CmsBundle\Security\EditableRolesBuilder
    arguments:
      - '@security.token_storage'
      - '@security.authorization_checker'
      - '@sonata.admin.pool'
      - '%wd_cms.cms%'
      - '%security.role_hierarchy.roles%'

  WebEtDesign\CmsBundle\Services\CmsHelper:
    public: true

  cms.helper:
    alias: WebEtDesign\CmsBundle\Services\CmsHelper

  # ===============================================
  # Menu
  # ===============================================

#  WebEtDesign\CmsBundle\Admin\BreadcrumbsBuilder\PageBreadcrumbsBuilder:
#    autowire: true
#    public: true

  WebEtDesign\CmsBundle\Admin\BreadcrumbsBuilder\MenuBreadcrumbsBuilder:
    autowire: true
    public: true

  # ===============================================
  # CKEditor Renderer
  # ===============================================

# Uncomment : MAJ sf6, obselet
#  fos_ck_editor.renderer:
#    class: WebEtDesign\CmsBundle\Services\CKEditorRenderer
#    arguments:
#      - '@fos_ck_editor.builder.json_builder'
#      - '@router'
#      - '@assets.packages'
#      - '@request_stack'
#      - "@=container.has('twig') ? container.get('twig') : container.get('templating')"
#      - "@=container.hasParameter('locale') ? parameter('locale') : null"
#    public: true

  # ===============================================
  # TWIG EXTENSION
  # ===============================================

  cms.twig.extension:
    class: WebEtDesign\CmsBundle\Twig\CmsTwigExtension
    tags:
      - { name: twig.extension }
    public: true
