parameters:
  cms.admin.cms_page_listener.class: WebEtDesign\CmsBundle\EventListener\PageAdminListener
  cms.admin.cms_site_listener.class: WebEtDesign\CmsBundle\EventListener\SiteAdminListener
  cms.admin.cms_shared_block_listener.class: WebEtDesign\CmsBundle\EventListener\SharedBlockAdminListener
  cms.admin.cms_site_entity_listener.class: WebEtDesign\CmsBundle\EventListener\CmsSiteListener

services:
  cms.user.validator.password_strength:
    class: WebEtDesign\Validator\Constraints\PasswordStrengthValidator
    arguments:
      - '@translator'
    tags:
      - { name: validator.constraint_validator, alias: password_strength }

  WebEtDesign\CmsBundle\Collectors\CmsCollector:
    tags:
      -
        name:     data_collector
        template: '@WebEtDesignCms/collectors/template.html.twig'
        id:       'cms.collector'
    arguments:
      - '@cms.helper'
      - '@cms.page_provider'
      - '@cms.admin.cms_page'
      - '@cms.admin.cms_page_declination'
      - '%wd_cms.cms%'

  WebEtDesign\CmsBundle\Form\PageTemplateType:
    arguments:
      - '@cms.page_provider'
    tags:
      - { name: form.type }

  WebEtDesign\CmsBundle\Form\BlockTemplateType:
    arguments:
      - '@cms.block_provider'
    tags:
      - { name: form.type }

  WebEtDesign\CmsBundle\Form\MultilingualType:
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '%wd_cms.admin.config.entity.page%'
      - '%wd_cms.admin.config.entity.site%'
    tags:
      - { name: form.type }

  WebEtDesign\CmsBundle\Form\GlobalVarsType:
    arguments:
      - '@cms.page_provider'
      - '@service_container'
      - '%wd_cms.vars%'
    tags:
      - { name: form.type }

  WebEtDesign\CmsBundle\Form\CmsRouteParamsType:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%wd_cms.cms%'
    tags:
      - { name: form.type }

  cms.routing_loader:
    class: WebEtDesign\CmsBundle\Routing\ExtraLoader
    public: true
    arguments: ['@doctrine.orm.entity_manager', '@parameter_bag', '%wd_cms.cms%']
    tags:
      - { name: routing.loader }

  cms.helper:
    class: WebEtDesign\CmsBundle\Services\CmsHelper
    arguments: ['@doctrine.orm.entity_manager', '@cms.page_provider', '@twig', "@security.authorization_checker", '@security.role_hierarchy']
    public: true

  WebEtDesign\CmsBundle\Services\TemplateProvider:
    arguments:
      $config: '%wd_cms.templates%'

  cms.page_provider:
    alias: WebEtDesign\CmsBundle\Services\TemplateProvider
    public: true

  cms.block_provider:
    class: WebEtDesign\CmsBundle\Services\TemplateProvider
    arguments:
      $config: '%wd_cms.shared_block%'

  WebEtDesign\CmsBundle\Utils\SitemapIterator:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@router'

  cms.security.editable_role_builder:
    class: WebEtDesign\CmsBundle\Security\EditableRolesBuilder
    arguments:
      - '@security.token_storage'
      - '@security.authorization_checker'
      - '@sonata.admin.pool'
      - '%wd_cms.cms%'
      - '%security.role_hierarchy.roles%'


  # ===============================================
  # CKEditor Renderer
  # ===============================================

  fos_ck_editor.renderer:
    class: WebEtDesign\CmsBundle\Services\CKEditorRenderer
    arguments:
      - '@fos_ck_editor.builder.json_builder'
      - '@router'
      - '@assets.packages'
      - '@request_stack'
      - "@=container.has('twig') ? container.get('twig') : container.get('templating')"
      - "@=container.hasParameter('locale') ? parameter('locale') : null"
    public: true

  # ===============================================
  # TWIG EXTENSION
  # ===============================================

  cms.twig.extension:
    class: WebEtDesign\CmsBundle\Twig\CmsTwigExtension
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@router'
      - '@service_container'
      - '@twig'
      - '@cms.page_provider'
      - '@cms.block_provider'
      - '@request_stack'
      - '@parameter_bag'
    tags:
      - { name: twig.extension }
    public: true

  # ===============================================
  # REPOSITORY
  # ===============================================

  WebEtDesign\CmsBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    tags: ['doctrine.repository_service']

  WebEtDesign\CmsBundle\Controller\SitemapController:
    arguments:
      - '@WebEtDesign\CmsBundle\Repository\CmsSiteRepository'
    tags: ['controller.service_arguments']
