parameters:
  cms.admin.cms_page_listener.class: WebEtDesign\CmsBundle\EventListener\PageAdminListener
  cms.admin.cms_site_listener.class: WebEtDesign\CmsBundle\EventListener\SiteAdminListener
  cms.admin.cms_shared_block_listener.class: WebEtDesign\CmsBundle\EventListener\SharedBlockAdminListener

services:
  _defaults:
    autowire: true
    autoconfigure: true

  WebEtDesign\CmsBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection'
      - '../../Entity'
      - '../../Twig'
      - '../../Sitemap'

  WebEtDesign\CmsBundle\Services\CustomContents\SharedBlockContent:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@cms.block_provider'
      - '@twig'
    public: true

  WebEtDesign\CmsBundle\Services\CustomContents\SharedBlockCollectionContent:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@cms.block_provider'
      - '@twig'
    public: true

  # ===============================================
  # REPOSITORY
  # ===============================================

  WebEtDesign\CmsBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    tags: [ 'doctrine.repository_service' ]


  # ===============================================
  # MISCELLANEOUS
  # ===============================================

  WebEtDesign\CmsBundle\Collectors\CmsCollector:
    tags:
      - name: data_collector
        template: '@WebEtDesignCms/collectors/template.html.twig'
        id: 'cms.collector'
    arguments:
      - '@cms.helper'
      - '@cms.page_provider'
      - '@cms.admin.cms_page'
      - '@cms.admin.cms_page_declination'
      - '%wd_cms.cms%'

  cms.routing_loader:
    class: WebEtDesign\CmsBundle\Routing\ExtraLoader
    public: true
    arguments: [ '@doctrine.orm.entity_manager', '@parameter_bag', '%wd_cms.cms%' ]
    tags:
      - { name: routing.loader }


  WebEtDesign\CmsBundle\Utils\SitemapIterator:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@router'

  cms.security.editable_role_builder:
    class: WebEtDesign\CmsBundle\Security\EditableRolesBuilder
    arguments:
      - '@security.token_storage'
      - '@security.authorization_checker'
      - '@sonata.admin.pool'
      - '%wd_cms.cms%'
      - '%security.role_hierarchy.roles%'

  WebEtDesign\CmsBundle\Services\CmsHelper:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@cms.page_provider'
      - '@twig'
      - "@security.authorization_checker"
      - '@security.role_hierarchy'
      - '@security.token_storage'
      - '@parameter_bag'
      - '@request_stack'
    public: true

  cms.helper:
    alias: WebEtDesign\CmsBundle\Services\CmsHelper

  # ===============================================
  # CMS provider
  # ===============================================

  WebEtDesign\CmsBundle\Services\TemplateProvider:
    arguments:
      $config: '%wd_cms.templates%'

  cms.page_provider:
    alias: WebEtDesign\CmsBundle\Services\TemplateProvider
    public: true

  cms.block_provider:
    class: WebEtDesign\CmsBundle\Services\TemplateProvider
    arguments:
      $config: '%wd_cms.shared_block%'

  # ===============================================
  # Menu
  # ===============================================

  WebEtDesign\CmsBundle\Admin\BreadcrumbsBuilder\PageBreadcrumbsBuilder:
    autowire: true
    public: true

  WebEtDesign\CmsBundle\Admin\BreadcrumbsBuilder\MenuBreadcrumbsBuilder:
    autowire: true
    public: true

  # ===============================================
  # CKEditor Renderer
  # ===============================================

  fos_ck_editor.renderer:
    class: WebEtDesign\CmsBundle\Services\CKEditorRenderer
    arguments:
      - '@fos_ck_editor.builder.json_builder'
      - '@router'
      - '@assets.packages'
      - '@request_stack'
      - "@=container.has('twig') ? container.get('twig') : container.get('templating')"
      - "@=container.hasParameter('locale') ? parameter('locale') : null"
    public: true

  # ===============================================
  # TWIG EXTENSION
  # ===============================================

  cms.twig.extension:
    class: WebEtDesign\CmsBundle\Twig\CmsTwigExtension
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@router'
      - '@service_container'
      - '@twig'
      - '@cms.page_provider'
      - '@cms.block_provider'
      - '@request_stack'
      - '@parameter_bag'
      - '@WebEtDesign\MediaBundle\Services\WDMediaService'
      - '@WebEtDesign\CmsBundle\Services\WDDeclinationService'
    tags:
      - { name: twig.extension }
    public: true



  WebEtDesign\CmsBundle\Controller\SitemapController:
    arguments:
      - '@WebEtDesign\CmsBundle\Repository\CmsSiteRepository'
    tags: [ 'controller.service_arguments' ]
