WebEtDesign\CmsBundle\Entity\CmsContentSlider:
    type: entity
    table: cms__content_slider
    repositoryClass: WebEtDesign\CmsBundle\Repository\CmsContentSliderRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        url:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    manyToOne:
        content:
            targetEntity: WebEtDesign\CmsBundle\Entity\CmsContent
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: sliders
            joinColumns:
                content_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
