WebEtDesign\CmsBundle\Entity\CmsContent:
    type: entity
    table: cms__content
    repositoryClass: WebEtDesign\CmsBundle\Repository\CmsContentRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        label:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        type:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        value:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0

    oneToMany:
        slider:
            targetEntity: WebEtDesign\CmsBundle\Entity\CmsContentSlider
            cascade:
                - persist
                - remove
            fetch: LAZY
            mappedBy: content
            inversedBy: null
            orphanRemoval: false
            orderBy: null

    manyToOne:
        page:
            targetEntity: WebEtDesign\CmsBundle\Entity\CmsPage
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: contents
            joinColumns:
                page_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
