WebEtDesign\CmsBundle\Entity\CmsSite:
    type: entity
    table: cms__site
    repositoryClass: WebEtDesign\CmsBundle\Repository\CmsSiteRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        locale:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        host:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        hostMultilingual:
            type: boolean
            nullable: false
            options:
                default: 0
        default:
            column: '`default`'
            type: boolean
            nullable: false
            options:
                default: 0
        flagIcon:
            type: string
            nullable: true
    lifecycleCallbacks: {  }
