WebEtDesign\CmsBundle\Entity\CmsSharedBlock:
    type: entity
    table: cms__shared_block
    repositoryClass: WebEtDesign\CmsBundle\Repository\CmsSharedBlockRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            length: 255
            unique: false
            nullable: false
        label:
            type: string
            length: 255
            unique: false
            nullable: true
        template:
            type: string
            length: 255
            unique: false
            nullable: true
        active:
            type: boolean
            length: null
            unique: false
            nullable: false
            options:
                default: 0
        public:
            type: boolean
            length: null
            unique: false
            nullable: true
            options:
                default: 1
    oneToMany:
        contents:
            targetEntity: WebEtDesign\CmsBundle\Entity\CmsContent
            cascade:
                - remove
                - persist
            mappedBy: sharedBlockParent
        contentList:
            targetEntity: WebEtDesign\CmsBundle\Entity\CmsContentHasSharedBlock
            cascade:
                - remove
                - persist
            mappedBy: sharedBlock
    lifecycleCallbacks: {  }
