WebEtDesign\CmsBundle\Entity\CmsRoute:
    type: entity
    table: cms__route
    repositoryClass: WebEtDesign\CmsBundle\Repository\CmsRouteRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        methods:
            type: array
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        path:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        controller:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
    oneToOne:
        page:
            targetEntity: WebEtDesign\CmsBundle\Entity\CmsPage
            cascade: {  }
            fetch: LAZY
            mappedBy: route
            inversedBy: null
            joinColumns: {  }
            orphanRemoval: false
    lifecycleCallbacks: {  }
